name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs.yml'
      - 'web/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-website-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-website-

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
